/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMailOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconMailOutline']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YkAvatar: typeof import('@yike-design/ui/es')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui/es')['YkBadge']
    YkButton: typeof import('@yike-design/ui/es')['YkButton']
    YkSpace: typeof import('@yike-design/ui/es')['YkSpace']
    YkTheme: typeof import('@yike-design/ui/es')['YkTheme']
  }
}
